sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
env:
  - EXPRESS_VERSION='>= 5.0.0-alpha.1'
  - EXPRESS_VERSION=4
  - EXPRESS_VERSION=3
before_script:
  - npm install express@"$EXPRESS_VERSION"
